workflows:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/**/*'

scripts:
- changed-files:
  - any-glob-to-any-file: 'scripts/**/*'

homebrew:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/brew.yml'
