name: agents

on:
  workflow_dispatch:
  schedule:
    # run every hour
    - cron: "0 * * * *"

permissions:
  contents: read

jobs:
  run-agents:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@f0c161a9c071e36ce5f71597c0c8eab56d389a4a # v5
        with:
          go-version: '1.21'

      - name: Install Hurl
        run: |
          cd /tmp && curl -fsSL https://github.com/Orange-OpenSource/hurl/releases/download/$HURL_VERSION/hurl-$HURL_VERSION-x86_64-unknown-linux-gnu.tar.gz -o hurl.tar.gz
          sudo tar xzf hurl.tar.gz -C /usr/local/bin --strip-components=2 hurl-$HURL_VERSION-x86_64-unknown-linux-gnu/bin
          hurl --version
        env:
          # renovate: datasource=github-releases depName=Orange-OpenSource/hurl
          HURL_VERSION: 7.0.0

      - name: Build agents
        run: |
          cd agents
          go build -o bin/agents ./cmd/agents

      - name: Run agents with sample plan
        run: |
          cd agents
          ./bin/agents -plan testdata/sample-plan.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
