name: check-chromedriver-version

on:
  schedule:
    - cron: "12 0 * * 2"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Run version check
      run: .github/workflows/check-version.sh
