name: check-chromedriver-version

on:
  schedule:
    - cron: "12 0 * * 2"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run version check
      run: .github/workflows/check-version.sh
