name: chenrui.dev site check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read

jobs:
  site-check:
    runs-on: ubuntu-24.04
    steps:
      - name: test site
        run: wget --spider https://chenrui.dev
        continue-on-error: true
