name: delete-event

# Runs your workflow anytime someone deletes a `branch` or `tag`, which triggers the `delete` event.
on:
  delete

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: run build
        env:
          DELETED_REF: ${{ github.event.ref }}
          DELETED_REF_TYPE: ${{ github.event.ref_type }}
        run: |
          printf 'GITHUB_SHA is %s\n' "$GITHUB_SHA"
          printf 'GITHUB_REF is %s\n' "$GITHUB_REF"
          printf '%s - %s\n' "$DELETED_REF" "$DELETED_REF_TYPE"
