name: Bump formulae on schedule or request

on:
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: >
    ack
    activemq

jobs:
  autobump:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@d9eb31ee3a04cf43ea8b2586717803b619b1b8ac

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: 'chenrui333'

      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        continue-on-error: true
        with:
          token: ${{ secrets.REPO_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
