name: "Pull Request Labeler"

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
