name: lang-go

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lang-go.yml'

permissions:
  contents: read

jobs:
  show-go-version:
    name: Show Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.22'
          - '1.23'
          - '1.24.0-rc.1' # see discussions in https://github.com/actions/setup-go/issues/524

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.go }}

      - name: Display Go Version
        run: go version
