name: lint

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - '**/*.dockerfile'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - 'Dockerfile*'
      - '**/*.dockerfile'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

jobs:
  dockerfile-lint:
    name: Check Dockerfile formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: '1.23'

      - name: Install dockerfmt
        run: go install github.com/reteps/dockerfmt@latest

      - name: Check Dockerfile formatting
        run: make lint
