name: repository-dispatch

on:
  repository_dispatch:
    types: ["trigger-event"]

# how to test this workflow
# gh auth login, then ./scripts/repository-dispatch-trigger.sh

# run log result
# https://github.com/chenrui333/github-action-test/actions/runs/161112535

env:
  ID: ${{ github.event.client_payload.id }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: show context
        run: |
          printf 'github sha is %s\n' "$GITHUB_SHA"
          cat "$GITHUB_EVENT_PATH"
          printf 'github.event_name is %s\n' "$GITHUB_EVENT_NAME"
      - name: run build
        if: github.event_name == 'repository_dispatch'
        env:
          INTEGRATION: ${{ github.event.client_payload.integration }}
        run: |
          printf 'id is %s\n' "$ID"
          printf 'integration is %s\n' "$INTEGRATION"

  show-id:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: show id
        run: |
          echo "id is $ID"
